name: Build and Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck
      
    - name: build Source
      run: g++ -Wall -Wextra -Werror --coverage -o SourceExe Source.cpp
      
    - name: run
      run: ./SourceExe

    - name: build DataSeparator
      run: g++ -Wall -Wextra -Werror --coverage -o ParserExe DataSeparator.cpp
    
    - name: run
      run: ./ParserExe
 
    - name: static analysis
      run: cppcheck --enable=all --check-config --error-exitcode=1 .
     
    - name: coverage report Source

      run: gcov -r Source.cpp

    - name: coverage report DataSeparator

      run: gcov -r DataSeparator.cpp
